### ISSUE TITLE
--preview wont work on ubuntu / pop-OS

### ISSUE THREAD

**Issue by codeitlikemiley** [Ancurio/colorpicker#6]
Sorry i cannot post issue on jacks fork so im posting here Instead

Hi  tried to installed all dependencies 
i installed in ubuntu

sudo apt install
```
gnome-devel
xorg
libxfixes-dev (libxfixes
libxcomposite-dev
lib32-libxcomposite
libcairo2-dev
libexext-dev
libgtk-2.0-dev
libgdk-pixbuf2.0-0
libcanberra-gtk-module
libcanberra-gtk3-module
```

I can get the hex value in my clipboard after i click
but when i run the command
colorpicker --short --one-shot --preview | xsel -b

nothing is showing under my bottom left screen

Im using this package on archlinux never had some trouble with it,
I know preview is not of a big deal but it really helps if you can see the preview

Hope you have time to read this, and check if there is a fix on this thanks

**Comment by Ancurio** [comment]
Apparently, instead of addressing the stated issues, the person behind #4 just went ahead and packaged their fork for Arch? Is that where you originally got the program from? I cannot help you with this at this point in time, maybe if the feature in the fork makes it into mainline, I'll reopen.
